package src.bmtamas;

public enum Ability {
    FISHERMAN,
    MANIAC,
    GUNSLINGER,
    SUBURB_KID,
    BOUNTY_HUNTER,
    ANOREXIC,
    THE_CAPITALIST,
    THE_ROCK,
    SURVIVALIST,
    BANDIT_LEADER,
    IMPERIAL_MUTANT_DEVASTATOR,
    ADHD,
    THE_LIVING_SNIPER,
    BURGLAR,
    MUTANT_LEADER,
    GLUTTONOUS,
    MEDIC,
    KLEPTOMANIAC_MARTIAL_ARTIST


}
